apiVersion: v1
kind: Service
metadata:
  name: cf-ssh-ingress
  namespace: paasta
spec:
  selector:
    cf-ssh: foo
  ports:
  - name: ssh
    nodePort: 30822
    port: 2222
    protocol: TCP
    targetPort: 2222
  sessionAffinity: None
  type: NodePort
